apiVersion: v1
kind: ConfigMap
metadata:
  name: <NAME OF THE ConfigMap>
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: mypassword
type: Opaque
data:
  <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>